FROM node:14.14.0

RUN apt install libtinfo5 libncurses5-dev
# WORKDIR /home/node/app
# ENV PATH $PATH:/home/node/app/node_modules/.bin
# COPY --chown=node:node package.json yarn.lock ./
# RUN yarn install
# USER node
# COPY --chown=node:node . ./
# RUN spago install halogen
