version: '3.8'
services:
  app:
    build: .
    environment:
      HTTPS_METHOD: noredirect
      VIRTUAL_HOST: '*.dev.hanach.in'
    volumes:
      - '.:/home/ubuntu/app'
    expose:
      - '9292'
    networks:
      - default
      - nginxproxy_default
    stdin_open: true
    tty: true

  pure:
    build:
      context: .
      dockerfile: Dockerfile.pure
    networks:
      - default
      - nginxproxy_default
    stdin_open: true
    tty: true
    volumes:
      - '.:/home/node/app'

networks:
  nginxproxy_default:
    external:
      name: nginxproxy_default
